name: E2E Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Build applications
        run: |
          cd proofofcombat-server && yarn install --frozen-lockfile && yarn generate
          cd ../proofofcombat-ui && yarn install --frozen-lockfile && yarn playwright install --with-deps

      - name: Run E2E tests
        run: |
          cd proofofcombat-ui && yarn playwright test --reporter=html,line
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: proofofcombat-ui/playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: test-results/
          retention-days: 7 